<div class="row app-menu">
    <div class="col-3">
        <svg
            width="300"
            height="150"
            viewBox="0 0 210 297"
            version="1.1"
            id="svg3705"
            inkscape:version="0.92.2 5c3e80d, 2017-08-06"
            sodipodi:docname="logo1.svg">
        <defs
            id="defs3699">
            <linearGradient
            id="linearGradient5996"
            osb:paint="solid">
            <stop
                style="stop-color:#000000;stop-opacity:1;"
                offset="0"
                id="stop5994" />
            </linearGradient>
        </defs>

        <g
            inkscape:label="logoD"
            inkscape:groupmode="layer"
            id="logoD">
            <text
            xml:space="preserve"
            style="font-style:normal;font-variant:normal;font-weight:bold;font-stretch:normal;font-size:196.06163025px;line-height:1.25;font-family:sans-serif;-inkscape-font-specification:'sans-serif Bold';letter-spacing:0px;word-spacing:0px;fill:#000000;fill-opacity:1;fill-rule:nonzero;stroke:#dc0000;stroke-width:3.06346297;stroke-opacity:1"
            x="-204.97496"
            y="150.67369"
            id="text3727"
            transform="scale(0.89784191,1.1137818)"><tspan
                sodipodi:role="line"
                id="tspan3725"
                x="-204.97496"
                y="324.14227"
                style="font-style:normal;font-variant:normal;font-weight:bold;font-stretch:normal;font-family:sans-serif;-inkscape-font-specification:'sans-serif Bold';fill:#000000;fill-opacity:1;fill-rule:nonzero;stroke:#dc0000;stroke-width:3.06346297;stroke-opacity:1" /></text>
        </g>
        <g
            inkscape:groupmode="layer"
            id="logoC"
            inkscape:label="logoC">
            <text
            xml:space="preserve"
            style="font-style:normal;font-variant:normal;font-weight:bold;font-stretch:normal;font-size:195.04875183px;line-height:1.25;font-family:sans-serif;-inkscape-font-specification:'sans-serif Bold';letter-spacing:0px;word-spacing:0px;fill:#000000;fill-opacity:1;stroke:#dc0000;stroke-width:3.04763675;stroke-opacity:1"
            x="-156.60959"
            y="241.60471"
            id="text3723"
            transform="scale(0.9351268,1.0693737)"><tspan
                sodipodi:role="line"
                id="tspan3721"
                x="-156.60959"
                y="414.17712"
                style="font-style:normal;font-variant:normal;font-weight:bold;font-stretch:normal;font-family:sans-serif;-inkscape-font-specification:'sans-serif Bold';stroke:#dc0000;stroke-width:3.04763675;stroke-opacity:1" /></text>
            <text
            xml:space="preserve"
            style="font-style:normal;font-variant:normal;font-weight:bold;font-stretch:normal;font-size:202.72024536px;line-height:1.25;font-family:monospace;-inkscape-font-specification:'monospace, Bold';font-variant-ligatures:normal;font-variant-caps:normal;font-variant-numeric:normal;font-feature-settings:normal;text-align:start;letter-spacing:0px;word-spacing:0px;writing-mode:lr-tb;text-anchor:start;fill:#c11207;fill-opacity:1;stroke:#000000;stroke-width:2.97288418;stroke-miterlimit:4;stroke-dasharray:none;stroke-opacity:1"
            x="-111.20504"
            y="266.4519"
            id="logoC"
            transform="matrix(0.96208025,-0.00130202,0.00254958,1.0394109,0,0)"
            inkscape:label=""><tspan
                sodipodi:role="line"
                id="tspan6073"
                x="-111.20504"
                y="266.4519"
                style="font-style:normal;font-variant:normal;font-weight:normal;font-stretch:normal;font-size:202.72024536px;font-family:monospace;-inkscape-font-specification:monospace;font-variant-ligatures:normal;font-variant-caps:normal;font-variant-numeric:normal;font-feature-settings:normal;text-align:start;writing-mode:lr-tb;text-anchor:start;fill:#c11207;fill-opacity:1;stroke:#000000;stroke-width:2.97288418;stroke-miterlimit:4;stroke-dasharray:none;stroke-opacity:1">C</tspan></text>
        </g>
        <g
            inkscape:groupmode="layer"
            id="layer2"
            inkscape:label="brand">
            <text
            xml:space="preserve"
            style="font-style:normal;font-variant:normal;font-weight:bold;font-stretch:normal;font-size:211.98094177px;line-height:1.25;font-family:sans-serif;-inkscape-font-specification:'sans-serif Bold';letter-spacing:0px;word-spacing:0px;fill:#00002e;fill-opacity:1;stroke:#010000;stroke-width:3.08689094;stroke-miterlimit:4;stroke-dasharray:none;stroke-opacity:1;image-rendering:auto"
            x="-134.14069"
            y="200.81995"
            id="logoD"
            transform="matrix(0.96798982,-0.00137577,0.00241291,1.0330653,0,0)"
            inkscape:label=""><tspan
                sodipodi:role="line"
                id="tspan6069"
                x="-134.14069"
                y="200.81995"
                style="font-style:normal;font-variant:normal;font-weight:normal;font-stretch:normal;font-size:211.98094177px;font-family:monospace;-inkscape-font-specification:monospace;font-variant-ligatures:normal;font-variant-caps:normal;font-variant-numeric:normal;font-feature-settings:normal;text-align:start;writing-mode:lr-tb;text-anchor:start;fill:#00002e;fill-opacity:1;stroke:#010000;stroke-width:3.08689094;stroke-miterlimit:4;stroke-dasharray:none;stroke-opacity:1">D</tspan></text>
            <flowRoot
            xml:space="preserve"
            id="flowRoot3709"
            style="font-style:normal;font-weight:bold;font-size:40px;line-height:1.25;font-family:sans-serif;letter-spacing:0px;word-spacing:0px;fill:#000000;fill-opacity:1;stroke:none;-inkscape-font-specification:'sans-serif Bold';font-stretch:normal;font-variant:normal;"
            transform="scale(0.26458333)"><flowRegion
                id="flowRegion3711"
                style="-inkscape-font-specification:'sans-serif Bold';font-family:sans-serif;font-weight:bold;font-style:normal;font-stretch:normal;font-variant:normal;"><rect
                id="rect3713"
                width="377.14285"
                height="211.42857"
                x="342.85715"
                y="276.80539"
                style="-inkscape-font-specification:'sans-serif Bold';font-family:sans-serif;font-weight:bold;font-style:normal;font-stretch:normal;font-variant:normal;" /></flowRegion><flowPara
                id="flowPara3715"></flowPara></flowRoot>    <text
            xml:space="preserve"
            style="font-style:normal;font-variant:normal;font-weight:bold;font-stretch:normal;font-size:102.73096466px;line-height:1.25;font-family:sans-serif;-inkscape-font-specification:'sans-serif Bold';letter-spacing:0px;word-spacing:0px;fill:#000000;fill-opacity:1;stroke:none;stroke-width:2.56827402"
            x="30.252832"
            y="95.407784"
            id="text3719"
            transform="scale(0.76271373,1.3111079)"><tspan
                sodipodi:role="line"
                id="tspan3717"
                x="30.252832"
                y="186.30061"
                style="font-style:normal;font-variant:normal;font-weight:bold;font-stretch:normal;font-size:79.19999695px;line-height:0.25;font-family:sans-serif;-inkscape-font-specification:'sans-serif Bold';stroke-width:2.56827402" /></text>
            <text
            xml:space="preserve"
            style="font-style:normal;font-weight:normal;font-size:126.72000122px;line-height:1.25;font-family:sans-serif;letter-spacing:0px;word-spacing:0px;fill:#000000;fill-opacity:1;stroke:none;stroke-width:1.98000002"
            x="156.09679"
            y="199.59677"
            id="text6059"><tspan
                sodipodi:role="line"
                id="tspan6057"
                x="156.09679"
                y="311.71426"
                style="stroke-width:1.98000002" /></text>
            <text
            xml:space="preserve"
            style="font-style:normal;font-variant:normal;font-weight:bold;font-stretch:normal;font-size:106.10081482px;line-height:1.25;font-family:sans-serif;-inkscape-font-specification:'sans-serif Bold';letter-spacing:0px;word-spacing:0px;fill:#000000;fill-opacity:1;stroke:none;stroke-width:3.9599998;stroke-miterlimit:4;stroke-dasharray:none"
            x="-0.76232755"
            y="255.28278"
            id="text6063"
            transform="scale(0.91634884,1.0912875)"><tspan
                sodipodi:role="line"
                id="tspan6061"
                x="-0.76232755"
                y="255.28278"
                style="font-size:66.31300354px;stroke:#010000;stroke-width:3.9599998;stroke-miterlimit:4;stroke-dasharray:none;stroke-opacity:1">ARPENTRY</tspan></text>
            <text
            xml:space="preserve"
            style="font-style:normal;font-variant:normal;font-weight:bold;font-stretch:normal;font-size:106.10081482px;line-height:1.25;font-family:sans-serif;-inkscape-font-specification:'sans-serif Bold';letter-spacing:0px;word-spacing:0px;fill:#000000;fill-opacity:1;stroke:none;stroke-width:3.9599998;stroke-miterlimit:4;stroke-dasharray:none"
            x="-2.7868569"
            y="189.73264"
            id="text6067"
            transform="scale(0.91634884,1.0912875)"><tspan
                sodipodi:role="line"
                id="tspan6065"
                x="-2.7868569"
                y="189.73264"
                style="font-style:normal;font-variant:normal;font-weight:bold;font-stretch:normal;font-size:66.31386566px;font-family:sans-serif;-inkscape-font-specification:'sans-serif, Bold';font-variant-ligatures:normal;font-variant-caps:normal;font-variant-numeric:normal;font-feature-settings:normal;text-align:start;writing-mode:lr-tb;text-anchor:start;stroke:#010000;stroke-width:3.9599998;stroke-miterlimit:4;stroke-dasharray:none;stroke-opacity:1">ETAILS</tspan></text>
            </g>
        </svg>
    </div>
    <div class="col-9">
        <div class="row third-spc-menu"></div>
        <div class="row">
            <nav class="navbar navbar-inverse">
                <a class="nav-link" href="">H . O . M . E</a>
                <a class="nav-link" href="">P . H . O . T . O . S</a>
                <a class="nav-link" href="">A . B . O . U . T</a>
                <a class="nav-link" href="">C . O . N . T . A . C . T</a>
            </nav>
        </div>
    </div>    
</div>    
